Update enseivpnscript

diff --git a/EEN Installers/enseivpnscript b/EEN Installers/enseivpnscript
--- a/EEN Installers/enseivpnscript
+++ b/EEN Installers/enseivpnscript
@@ -555,13 +555,37 @@ echo '{
   "disable_udp": false,
   "obfs": "ensei",
   "auth": {
-    "mode": "passwords",
-    "config": ["enseivpn"]
-  }
+    "mode": "external",
+    "config": {
+    "cmd": "./.auth.sh"
+    }
 }
 ' >> /etc/hysteria/config.json
 
+cat <<"EOM" >/etc/hysteria/.auth.sh
+#!/bin/bash
+. /etc/openvpn/login/config.sh
+
+if [ $# -ne 4 ]; then
+    echo "invalid number of arguments"
+    exit 1
+fi
+
+ADDR=$1
+AUTH=$2
+SEND=$3
+RECV=$4
+
+USERNAME=$(echo "$AUTH" | cut -d ":" -f 1)
+PASSWORD=$(echo "$AUTH" | cut -d ":" -f 2)
+
+Query="SELECT user_name FROM users WHERE user_name='$USERNAME' AND auth_vpn=md5('$PASSWORD') AND status='live' AND is_freeze=0 AND is_ban=0 AND (duration > 0 OR vip_duration > 0 OR private_duration > 0)"
+user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
+[ "$user_name" != '' ] && [ "$user_name" = "$USERNAME" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
+EOM
+
 chmod 755 /etc/hysteria/config.json
+chmod 755 /etc/hysteria/.auth.sh
 
 sysctl -w net.core.rmem_max=16777216
 sysctl -w net.core.wmem_max=16777216
