Update enseivpnscript

diff --git a/EEN Installers/enseivpnscript b/EEN Installers/enseivpnscript
--- a/EEN Installers/enseivpnscript
+++ b/EEN Installers/enseivpnscript
@@ -548,8 +548,8 @@ rm -f /etc/hysteria/config.json
 
 echo '{
   "listen": ":5666",
-  "cert": "/etc/hysteria/hysteria.crt",
-  "key": "/etc/hysteria/hysteria.key",
+  "cert": "/etc/openvpn/easy-rsa/keys/server.crt",
+  "key": "/etc/openvpn/easy-rsa/keys/server.key",
   "up_mbps": 100,
   "down_mbps": 100,
   "disable_udp": false,
@@ -566,7 +566,27 @@ echo '{
 }
 ' >> /etc/hysteria/config.json
 
-wget -O /etc/hysteria/.auth.sh "https://raw.githubusercontent.com/Ensei09/EnseiVPN/main/EEN%20Installers/premium"
+cat <<"EOM" >/etc/hysteria/.auth.sh
+#!/bin/bash
+. /etc/openvpn/login/config.sh
+
+if [ $# -ne 4 ]; then
+    echo "invalid number of arguments"
+    exit 1
+fi
+
+ADDR=$1
+AUTH=$2
+SEND=$3
+RECV=$4
+
+USERNAME=$(echo "$AUTH" | cut -d ":" -f 1)
+PASSWORD=$(echo "$AUTH" | cut -d ":" -f 2)
+
+Query="SELECT user_name FROM users WHERE user_name='$USERNAME' AND auth_vpn=md5('$PASSWORD') AND status='live' AND is_freeze=0 AND is_ban=0 AND (duration > 0 OR vip_duration > 0 OR private_duration > 0)"
+user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
+[ "$user_name" != '' ] && [ "$user_name" = "$USERNAME" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
+EOM
 
 chmod 755 /etc/hysteria/config.json
 chmod 755 /etc/hysteria/.auth.sh
